# [SB] Speed Change:
# Edit the `test_time_velocity` and `maneuver_velocity` to the required speed. 
# Note that the ckpt we provide will work for all speeds in the range [1,10] m/s. 
# However, to reach the best performance at a specific speed, please consider finetuning the ckpt at the desired speed
general:
  control_command_delay: 0.02
  nw_predictions_frame_id: 1  # 0: world, 1: body
  num_traj_viz: 1000  # how many trajectories to visualize
  perform_global_planning: false
  test_time_velocity: 2.5
  test_time_max_z: 30.0
  test_time_min_z: 1.0
maneuver:
  length_straight: 40.0
  maneuver_velocity: 2.5
trajectory:
  traj_len: 10
  # traj_dt: 0.1
  traj_dt: 0.25 # 0.25 * 10 = 2.5 seconds
  continuity_order: 1 # 0: position, 1: velocity, 2: acceleration
  enable_yawing: true
# everything about saving data to disk
data_generation:
  save_freq: 15 # save images & odometry at this frequency

